CC = gcc
CFLAGS = -Wall -Wextra -Werror

all: state_sort

state_sort: ./state_sort.c
	$(CC) $(CFLAGS) -o state_sort ./state_sort.c

state_search: ./state_search.c
	$(CC) $(CFLAGS) -o state_search ./state_search.c